#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}


define('DEBUG', true);

// function getApp()
// {
//     return App\Application::getInstance();
// }

function getDI()
{
    return App\Application::getDI();
}

$app = App\Application::getInstance();
$app->run();
