#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../vendor/autoload.php')) {
    require __DIR__.'/../../vendor/autoload.php';//.composer
} elseif (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';//app
} else {
    die("not exists vendor");
}


define('DEBUG', true);

// function getApp()
// {
//     return App\Application::getInstance();
// }

function getDI()
{
    return App\Application::getDI();
}

$app = App\Application::getInstance();
$app->run();
