#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

define('DEBUG', true);

// function getApp()
// {
//     return App\Application::getInstance();
// }

function getDI()
{
    return App\Application::getDI();
}

$app = App\Application::getInstance();
$app->run();
