parameters:

services:
    server.ssh:
        class:  App\server\Ssh
    console:
        class:  Symfony\Component\Console\Application
    console.test:
        class: \App\console\Test
    console.demo:
        class: \App\console\Demo
    console.log:
        class: \App\console\Log
    console.gl:
        class: \App\console\Gl
    console.diy:
        class: \App\console\Diy
    console.online:
        class: \App\console\Online
